version: "3.8"
services:
  axonserver-development:
    image: axoniq/axonserver:4.5
    container_name: wedding-invitations-axonserver-development
    ports:
      - "8024:8024"
      - "8124:8124"
    restart: on-failure
    volumes:
      - wedding-invitations-axonserver-development-data:/data
      - wedding-invitations-axonserver-development-eventdata:/eventdata
  postgres-development:
    image: postgres:13.3
    container_name: wedding-invitations-postgres-development
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_DB: wedding-invitations
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - wedding-invitations-postgres-development:/var/lib/postgresql/data
volumes:
  wedding-invitations-axonserver-development-data:
  wedding-invitations-axonserver-development-eventdata:
  wedding-invitations-postgres-development:
