server:
  port: 8001
spring:
  application:
    name: WeddingInvitations
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wedding-invitations
    username: user
    password: password
  jooq:
    sql-dialect: postgres
logging:
  level:
    org:
      jooq:
        Constants: WARN
---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: production
