server:
  port: 8001
spring:
  application:
    name: WeddingInvitations
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wedding-invitations
    username: user
    password: password
  jooq:
    sql-dialect: postgres
  sendgrid:
    api-key: REPLACE_ME
discord:
  webhook-uri: REPLACE_ME
google-sheets:
  spreadsheet-id: REPLACE_ME
web-app:
  invitation-url-prefix: REPLACE_ME
logging:
  level:
    org:
      jooq:
        Constants: WARN
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: production
